### ISSUE TITLE
Discord bot 動作したまましばらく放置すると SEGV

### ISSUE THREAD

**Issue by yappy** [yappy/DollsKit#65]
```
[New Thread 0xab3f8220 (LWP 6652)]
[Thread 0xab3f8220 (LWP 6652) exited]
Sun Jan 31 00:38:01 2021 (2986340896) [Info ]: [Twitter] finish (OK)
Sun Jan 31 00:39:00 2021 (3052683280) [Trace]: wake up
Sun Jan 31 00:39:00 2021 (3052683280) [Trace]: finalize future
Sun Jan 31 00:39:00 2021 (3052683280) [Trace]: finalize future
Sun Jan 31 00:39:00 2021 (3052683280) [Trace]: sleep for 60 sec
Sun Jan 31 00:40:00 2021 (3052683280) [Trace]: wake up
Sun Jan 31 00:40:00 2021 (3052683280) [Trace]: finalize future
Sun Jan 31 00:40:00 2021 (3052683280) [Trace]: sleep for 60 sec
Sun Jan 31 00:41:00 2021 (3052683280) [Trace]: wake up
Sun Jan 31 00:41:00 2021 (3052683280) [Trace]: finalize future
Sun Jan 31 00:41:00 2021 (3052683280) [Trace]: sleep for 60 sec
Sun Jan 31 00:42:00 2021 (3052683280) [Trace]: wake up
Sun Jan 31 00:42:00 2021 (3052683280) [Trace]: finalize future
Sun Jan 31 00:42:00 2021 (3052683280) [Trace]: sleep for 60 sec

Thread 6 "shanghai" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb4de9220 (LWP 6114)]
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0x0001dcbc in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)1>::_M_release() ()
#2  0x000eb1cc in asio::detail::wait_handler<std::_Bind<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*(websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>))(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> >::do_complete(void*, asio::detail::scheduler_operation*, std::error_code const&, unsigned int) ()
#3  0x00029c08 in asio::detail::scheduler::run(std::error_code&) ()
#4  0x000d41e8 in SleepyDiscord::WebsocketppDiscordClient::run() ()
#5  0x00026834 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<shanghai::system::Discord::Discord()::{lambda()#1}> > >::_M_run() ()
#6  0xb6bc69b0 in ?? () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#7  0xb6a56494 in start_thread (arg=0xb4de9220) at pthread_create.c:486
#8  0xb69d9578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) bt 0xb4de9220
#0  0x00000000 in ?? ()
#1  0x0001dcbc in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)1>::_M_release() ()
#2  0x000eb1cc in asio::detail::wait_handler<std::_Bind<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*(websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>))(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> >::do_complete(void*, asio::detail::scheduler_operation*, std::error_code const&, unsigned int) ()
#3  0x00029c08 in asio::detail::scheduler::run(std::error_code&) ()
#4  0x000d41e8 in SleepyDiscord::WebsocketppDiscordClient::run() ()
#5  0x00026834 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<shanghai::system::Discord::Discord()::{lambda()#1}> > >::_M_run() ()
#6  0xb6bc69b0 in ?? () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#7  0xb6a56494 in start_thread (arg=0xb4de9220) at pthread_create.c:486
#8  0xb69d9578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(
```

**Comment by yappy** [comment]
#66 での解決後、見ていない。
おそらく同根。
